In [1]:
# 1 create array np.array() function.
import numpy as np
 
array1d = np.array([1, 5, 4, 3, 7, 6])
array2d = np.array([[1, 2, 3], [7, 5, 6]])
array3d = np.array([[[1, 8, 4], [4, 5, 9]], [[3, 2, 6], [12, 10, 14]]])
 
print(array1d)
 
print("-" * 10)
print(array2d)
 
print("-" * 10)
print(array3d)

[1 5 4 3 7 6]
----------
[[1 2 3]
 [7 5 6]]
----------
[[[ 1  8  4]
  [ 4  5  9]]

 [[ 3  2  6]
  [12 10 14]]]


In [3]:
import numpy as np
# 2 
type1 = np.array([1, 8, 5, 4, 6, 9])
type2 = np.array([3.5, 4.5, 2.5, 7])
type3 = np.array(['a', 'b', 'c'])

print(type1.dtype)
print(type2.dtype)
print(type3.dtype)

int32
float64
<U1


In [4]:
import numpy as np
 # 3, 4 The shape method determines the shape of NumPy array in form of (m, n) i.e (no. of rows) x (no. of columns).
arr1d = np.array([11, 22, 34, 43, 52, 61])
arr2d = np.array([[1, 24, 37], [46, 54, 63]])
arr3d = np.array([[[14, 52, 36], [47, 55, 64]], [[73, 82, 93], [16, 19, 12]]])
 
print(arr1d.shape)
print(arr2d.shape)
print(arr3d.shape)

(6,)
(2, 3)
(2, 2, 3)


In [6]:
import numpy as np

 
#5 The ndim method determines the dimension of NumPy array.
arry1d = np.array([15, 23, 32, 34, 25, 6])
print(arry1d.ndim) 
 
arry2d = np.array([[81, 22, 7], [34, 45, 66]])
print(arry2d.ndim) 
 
arry3d = np.array([15, 26, 3, 4, 53, 61, 73, 8, 98, 15, 12, 19])
arry3d = arry3d.reshape(2, 3, 2)
print(arry3d.ndim)

1
2
3


In [7]:
import numpy as np

# 6 The resize() method modifies existing shape and array itself.
thearay = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearay.resize(4)
print(thearay)
 
print("-" * 10)
thearay = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearay.resize(2, 4)
print(thearay)
 

[1 2 3 4]
----------
[[1 2 3 4]
 [5 6 7 8]]


In [9]:
import numpy as np

# 7 reshape () method modifies existing shape but original array remains unchanged.
tarray = np.array([4, 2, 1, 6, 8, 9, 1, 0])
tarray = tarray.reshape(2, 4)
print(tarray)
 
print("-" * 10)
tarray = tarray.reshape(4, 2)
print(tarray)

[[4 2 1 6]
 [8 9 1 0]]
----------
[[4 2]
 [1 6]
 [8 9]
 [1 0]]


In [11]:
import numpy as np
 #8 The array() function can accept lists, tuples and other numpy.ndarray objects also to create new array object.
ttuple = ((9, 7, 0))
print(type(ttuple))
arry = np.array([ttuple])
print(arry)

<class 'tuple'>
[[9 7 0]]


In [14]:
import numpy as np

#9 The arange() function creates an array with evenly spaced values between the specified start, end, and increment values.
aray1d = np.arange(5)  
print(array1d)
aray2d = np.arange(0, 12, 2).reshape(2, 3)  
print(aray2d)

[0 1 2 3 4]
[[ 0  2  4]
 [ 6  8 10]]


In [15]:
import numpy as np
#10 The linspace() function generates an array with evenly space

arry = np.linspace(1, 12, 2)
print(arry)
arry = np.linspace(1, 12, 12).reshape(4, 3)
print(arry)

[ 1. 12.]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [17]:
import numpy as np
# 11 The logspace() function, generates an array with values that are logarithmical.

tarray = np.logspace(4, 9, num=11, base=10000000.0, dtype=float)
print(tarray)

[1.00000000e+28 3.16227766e+31 1.00000000e+35 3.16227766e+38
 1.00000000e+42 3.16227766e+45 1.00000000e+49 3.16227766e+52
 1.00000000e+56 3.16227766e+59 1.00000000e+63]


In [18]:
import numpy as np
# 12 The zeros() function, generates an array with the specified dimensions and data type that is filled with zeros.

aray = np.zeros(6)
print(aray)
 
aray1 = np.zeros((4, 2))
print(aray1)

[0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [20]:
import numpy as np
#13 The ones() function, generates an array with the specified dimensions and data type that is filled with ones. 

ary = np.ones(5)
print(ary)
 
ary1 = np.ones((5, 4))
print(ary1)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
import numpy as np
#14 generates an array with the specified dimensions and data type that is filled with specified number.

arrayd = np.full((3), 8)
print(arrayd)

[8 8 8]


In [23]:
import numpy as np

#15 The eye() function, returns an array where all elements are equal to zero, except for the k-th diagonal,
aray1 = np.eye(4, dtype=int)
print(aray1)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [26]:
import numpy as np
#16, 17, 18 
print(np.random.rand(1, 2))  # Uniformly distributed values.
print(np.random.randn(2, 3))  # Normally distributed values.
 
# Uniformly distributed integers in a given range.
print(np.random.randint(9, size=6))
print(np.random.randint(5, size=(4, 6)))

[[0.29859107 0.39530689]]
[[-1.29301494  0.1791978  -1.32302451]
 [ 0.06980506 -0.27637665  0.08596766]]
[4 4 3 5 8 8]
[[0 0 1 3 1 3]
 [0 2 1 1 0 1]
 [1 4 2 3 4 3]
 [2 2 4 1 0 0]]


In [27]:
import numpy as np
 
# 19, 20 The identity() function, generates square array with ones on the main diagonal 
# whereas diag() function extract or construct diagonal array.
print(np.identity(4))
 
print(np.diag(np.arange(0, 8, 2)))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0 0 0 0]
 [0 2 0 0]
 [0 0 4 0]
 [0 0 0 6]]


In [28]:
import numpy as np
 
array2d = np.array([[11, 32, 63], [84, 75, 65], [47, 38, 96]])
print(array2d)
 
print("-" * 10)
 
# 21 Permute the dimensions of an array.
arrayT = np.transpose(array2d)
print(arrayT)
 
print("-" * 10)
 
#22 Flip array in the left/right direction.
arrayFlr = np.fliplr(array2d)
print(arrayFlr)
 
print("-" * 10)
 
#23 Flip array in the up/down direction.
arrayFud = np.flipud(array2d)
print(arrayFud)
 
print("-" * 10)
 
#24 Rotate an array by 90 degrees in the plane specified by axes.
arrayRot90 = np.rot90(array2d)
print(arrayRot90)

[[11 32 63]
 [84 75 65]
 [47 38 96]]
----------
[[11 84 47]
 [32 75 38]
 [63 65 96]]
----------
[[63 32 11]
 [65 75 84]
 [96 38 47]]
----------
[[47 38 96]
 [84 75 65]
 [11 32 63]]
----------
[[63 65 96]
 [32 75 38]
 [11 84 47]]


In [30]:
import numpy as np
 
array1 = np.array([[4, 2, 1], [6, 8, 9]])
array2 = np.array([[0, 3, 5], [18, 16, 19]])
 
#25 Stack arrays in sequence horizontally (column wise).
arrayH = np.hstack((array1, array2))
print(arrayH)
 
print("-" * 15)
 
#26 Stack arrays in sequence vertically (row wise).
arrayV = np.vstack((array1, array2))
print(arrayV)
 
print("-" * 15)
 
#27 Stack arrays in sequence depth wise (along third axis).
arrayD = np.dstack((array1, array2))
print(arrayD)
 
print("-" * 15)
 
#28 Appending arrays after each other, along a given axis.
arrayC = np.concatenate((array1, array2))
print(arrayC)
 
print("-" * 15)
 
#29 Append values to the end of an array.
arrayA = np.append(array1, array2, axis=0)
print(arrayA)
 
print("-" * 15)
arrayA = np.append(array1, array2, axis=1)
print(arrayA)

[[ 4  2  1  0  3  5]
 [ 6  8  9 18 16 19]]
---------------
[[ 4  2  1]
 [ 6  8  9]
 [ 0  3  5]
 [18 16 19]]
---------------
[[[ 4  0]
  [ 2  3]
  [ 1  5]]

 [[ 6 18]
  [ 8 16]
  [ 9 19]]]
---------------
[[ 4  2  1]
 [ 6  8  9]
 [ 0  3  5]
 [18 16 19]]
---------------
[[ 4  2  1]
 [ 6  8  9]
 [ 0  3  5]
 [18 16 19]]
---------------
[[ 4  2  1  0  3  5]
 [ 6  8  9 18 16 19]]


In [2]:
import numpy as np
 
array1d = np.array([[4, 2, 1], [3, 5, 9]])
array2d = np.array([[17, 18, 19], [13, 16, 11]])
# 30 
print(array1d + array2d)
print("-" * 20)
# 31 
print(array1d - array2d)
print("-" * 20)
# 32 
print(array1d * array2d)
print("-" * 20)
# 33 
print(array2d / array1d)
print("-" * 40)
# 34 
print(array1d ** array2d)
print("-" * 40)

[[21 20 20]
 [16 21 20]]
--------------------
[[-13 -16 -18]
 [-10 -11  -2]]
--------------------
[[68 36 19]
 [39 80 99]]
--------------------
[[ 4.25        9.         19.        ]
 [ 4.33333333  3.2         1.22222222]]
----------------------------------------
[[          0      262144           1]
 [    1594323 -2030932031  1316288537]]
----------------------------------------


In [5]:
import numpy as np
# 35 
array1 = np.array([[11, 22, 33], [44, 54, 65]])
 
print(array1 + 3)
print("-" * 20)
# 36
print(array1 - 7)
print("-" * 20)

[[14 25 36]
 [47 57 68]]
--------------------
[[ 4 15 26]
 [37 47 58]]
--------------------


In [7]:
import numpy as np
 
arry1 = np.array([[12, 23, 34], [46, 57, 68]])
# 37 
print(np.sin(arry1))
print("-" * 40)
# 38 
print(np.cos(arry1))
print("-" * 40)
# 39 
print(np.tan(arry1))
print("-" * 40)
# 40  
print(np.sqrt(arry1))
print("-" * 40)
# 41 
print(np.exp(arry1))
print("-" * 40)
# 42 
print(np.log10(arry1))
print("-" * 40)

[[-0.53657292 -0.8462204   0.52908269]
 [ 0.90178835  0.43616476 -0.89792768]]
----------------------------------------
[[ 0.84385396 -0.53283302 -0.84857027]
 [-0.43217794  0.89986683  0.44014302]]
----------------------------------------
[[-0.63585993  1.58815308 -0.62349896]
 [-2.08661353  0.48469923 -2.0400816 ]]
----------------------------------------
[[3.46410162 4.79583152 5.83095189]
 [6.78232998 7.54983444 8.24621125]]
----------------------------------------
[[1.62754791e+05 9.74480345e+09 5.83461743e+14]
 [9.49611942e+19 5.68572000e+24 3.40427605e+29]]
----------------------------------------
[[1.07918125 1.36172784 1.53147892]
 [1.66275783 1.75587486 1.83250891]]
----------------------------------------


In [ ]:
import numpy as np
 
aray1d = np.array([[10, 20, 30], [40, 50, 60]])
 # 43
print("Mean: ", np.mean(aray1d))
 # 44
print("Std: ", np.std(aray1d))
 # 45
print("Var: ", np.var(aray1d))
 # 46
print("Sum: ", np.sum(aray1d))
 # 47
print("Prod: ", np.prod(aray1d))
 

In [8]:
import numpy as np
# 48 Useful functions for Conditional and Logical Expressions
# The where() function is used to chooses values from arrays depending on the value of a specific condition.
before = np.array([[1, 2, 3], [4, 5, 6]])
 
# If element is less than 4, mul by 2 else by 3
after = np.where(before < 4, before * 2, before * 3)
 
print(after)

[[ 2  4  6]
 [12 15 18]]


In [9]:
import numpy as np
# logical_or computes the truth value of x1 OR x2 element-wise. 
# logical_and computes the truth value of x1 AND x2 element-wise.
# logical_or computes the truth value of NOT x element-wise.
thearray = np.array([[12, 21, 34], [24, 54, 76]])
 #49
print(np.logical_or(thearray < 10, thearray > 15))
print("-" * 30)
 # 50
print(np.logical_and(thearray < 10, thearray > 15))
print("-" * 30)
 # 51
print(np.logical_not(thearray < 20))
print("-" * 30)

[[False  True  True]
 [ True  True  True]]
------------------------------
[[False False False]
 [False False False]]
------------------------------
[[False  True  True]
 [ True  True  True]]
------------------------------
